name: riverpod_inmutable
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^12.1.0
  flutter_riverpod: ^2.4.5
  freezed: ^2.3.2
  freezed_annotation: ^2.4.4
  intl: ^0.18.0
  riverpod_annotation:
  lorem_gen:


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  riverpod_generator:
  lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/app/detail/

